```{r}
output$contentsAdviceOutput = renderUI({
  text =  HTML("At the bottom, you can save your 'comments' and 'answers'. To resume in a new session, you can reload your saved content from your Downloads folder. Click here to locate them. (Only empty strings will be replaced.)")
  contentFileInput = function(
    label=c('comments','answers')) {
    #https://stackoverflow.com/questions/49506469/shiny-customise-fileinput?rq=1
    thisfileInput =
      fileInput(inputId = paste0(label,"FileInput"), 
              label = NULL,
              buttonLabel=paste0("Find _", label,
                             "_T15lumpsplit.txt"),
              accept = c(
                "text/csv",
                "text/comma-separated-values,text/plain")
      )
    thisfileInput$children[[2]]$children[[2]] = NULL
    assign(paste0(label, 'FileInput'), thisfileInput, pos=1)
    thisfileInput
  }
  div(
    tagAppendAttributes(
      span(text),
      style=paste(
        'display: flex; justify-content: flex-center;',
        'color:red; background: lightgrey;',
        'font-weight:bold; font-size:larger')),
    tagAppendAttributes(
      style=paste(
        'background: lightgrey;',
        'font-weight:bold; font-size:larger'),
      fluidRow(
        column(2, ""),
        column(4, contentFileInput('comments')),
        column(4, contentFileInput('answers'))
      )
    )
  )
})

div(
  
    uiOutput('contentsAdviceOutput')
    
)
```

```{r}
uiOutput('contentsAdvice')
```

```{r}
for(contentType in c('comments', 'answers'))
    assign(x=paste0('observeEvent_for_',contentType), pos=1,
         value=observeEvent(
           input[[paste0(contentType, 'FileInput')]], {
             print(paste0("Entering ", 'observeEvent_for_',contentType))
             inFile <- input[[paste0(contentType, 'FileInput')]]
             if (is.null(inFile))
               return(NULL)
             savedContents = read.csv(
               file = inFile$datapath, 
               header = TRUE,
               stringsAsFactors = FALSE)
             rValues[[paste0('saved', contentType)]] = savedContents
             if(contentType == 'comments'){
               the_contexts = QA_contexts
               the_prefix = 'idQA'
             }
             if(contentType == 'answers'){
               the_contexts = TQ_contexts
               the_prefix = 'idTQ'
             }
             for(contextNumber in seq(along=the_contexts) ) {
               contextID = paste0(the_prefix, contextNumber)
               context = the_contexts[[contextNumber]]
               cat("input ", contextID, "\n")
               print(paste(contextID, context, "===",
                           input[[contextID]]))
               retrievedcontext = savedContents[contextNumber, 'contexts']
               retrievedcontent = gsub('^ *', '',
                              savedContents[contextNumber, 'contents'])
               retrievedcontent = gsub('[1] *', '', fixed = TRUE, retrievedcontent)
               print(paste('retrieved: ', contextID, 
                           retrievedcontext, "===>", retrievedcontent))
               retrievedcontent = as.vector(retrievedcontent)
               retrievedcontent = strsplit(split='\n', retrievedcontent)[[1]]
               if(retrievedcontent != "") {
                 cat(" Placing ", retrievedcontent, ' into ',
                   retrievedcontext)
                 updateTextAreaInput(session = session,
                                     inputId = contextID,
                                     value = retrievedcontent)
               }
             }
           }
         )
  )
```


