---
title: "Bias, variance, smoothing, and shrinking"
output: 
  html_document:
    toc: true
    toc_float: 
      collapsed: false
      smooth_scroll: false
      number_sections: true
runtime: shiny
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(knitr.duplicate.label = 'allow')
#options(error=browser)
require(T15lumpsplit)
require(shiny)
#source('rstudio.markdownToHTML.R', local=TRUE)
```

```{r setup numbering, warning=FALSE}
try(rm(envNextNumber, pos=1), silent = TRUE)
try(rm(envNextNumberTOC, pos=1), silent = TRUE)
try(rm(envNextNumberQA, pos=1), silent = TRUE)
try(rm(envNextNumberTextQuestion, pos=1), silent = TRUE)
### Note that the .GlobalEnv seen here is different from your R session... and it persists across Rmd runs!
source('nextNumber.R', local=TRUE)
source('interactiveSection.R', local=TRUE)
source('QandAha.R', local=TRUE)
source('TextQuestion.R', local=TRUE)
```


```{r includeFunctions}
source('inclRmd.R', local=T)
source('linkout.R', local=T)
source('interactiveSection.R', local=T)
source('includeHTMLtrimmed.R', local=T)

```


```{r initial values, echo=FALSE}

logit = function(p) log(p/(1-p))
antilogit = function(x) 1 - 1/(1+exp(x))
DLdata = matrix(c(3,5,2,90),nrow=2)
dimnames(DLdata) = list(c("D","L"),c("R","N"))
ColorForPrior="orange";     
ColorForPosterior="blue";     
ColorForLikelihood="black"
TOCnum =  0
```

```{r navTOCid.R}
#source('navTOCid.R', local=T)
```


```{r servercode}
source("Plight-Pdark-posterior-new.R", local=TRUE)
source("DrWhoBayesFactor.R")
rValues = reactiveValues(tau = 1,  phi = 0.001, mu=0.5,
                         title_1='title 1',
                         DLdata = DLdata)
```

```{r plotPlightPdarkPosteriorReactive}
plotPlightPdarkPosteriorReactive = reactive( {
  cat("PLOTTING   ")
  tau <- input$tauInput
  phi <- input$phiInput
  mu0 <- input$mu0Input
  cat("tau=", tau, " phi=", phi, " mu0=", mu0, "\n")
  plotPlightPdarkPosterior(DLdata=rValues$DLdata,
                           tau=tau, phi=phi, mu0=logit(mu0), 
                           fudgeFactor = input$fudgeFactor)
  rValues$title_3 <<- paste0(
    "  tau=", input$tauInput,  
    ",  phi=", input$phiInput,  
    ",  mu0=", input$mu0Input 
  )
})
```


```{r lumpReact}
lumpReact = observe({
  if(length(input$lumpID) > 0) {
    cat("lumpID\n")
    rValues$tau <- 1; rValues$phi <- 0.001   
    ### Lump:  no individual variation:   D is same as L.
    rValues$title_1 <- "Dr. Lump"
    rValues$title_2 <- HTML("Prior belief: <br>Pr(R|D) = Pr(R|L)")
  }
})  
```

```{r updateDLdata}
updateDLdata = observe({
    try(silent = TRUE, {
        rValues$DLdata[1,1] =  input$mRD
        rValues$DLdata[1,2] =  input$mND
        rValues$DLdata[2,1] =  input$mRL
        rValues$DLdata[2,2] =  input$mNL
    })
  cat('input$mRD', input$mRD, '\n')
})
```

```{r splitReact}
splitReact = observe({
  if(length(input$splitID) > 0) {
    cat("splitID\n")
    rValues$tau <<- 0; rValues$phi <<- 1   
    ### Split:  D unconnected to L.
    rValues$title_1 <<- "Dr. Split"
    rValues$title_2 <<- HTML("Prior belief:<br> Pr(R|D) is unrelated to Pr(R|L).")
  }
}) 
```

```{r whoReact}
whoReact = observe({
  if(length(input$whoID) > 0) {
    cat("whoID\n")
    ### Who:  discrete mixture of Lump and Split.
    rValues$title_1 <<- "Dr. Who: \ndiscrete mixture of Lump and Split."
    rValues$title_2 <<- HTML("Prior belief: <BR> Pr(Lump)=Pr(Split)=1/2.")
  }
}) 
```

```{r mixedReact} 
mixedReact = observe({
  if(length(input$mixedID) > 0) {
    cat("mixedID\n")
    rValues$tau <<- 1/2; rValues$phi <<- 1/2 
    rValues$title_1 <<- HTML("Compromise: <br>lump some, split some")
    rValues$title_2 <<- HTML("Prior belief: <br> Pr(R|D) is somewhat related to Pr(R|L). ")
  }
})
```

```{r updateViews}
updateViews = observe({
  updateNumericInput(session=session, inputId="tauInput", 
                     value = rValues$tau)
  updateNumericInput(session=session, inputId="phiInput", 
                     value = rValues$phi)
})
```


```{r thePlot}
output$title_1_ID = renderUI({rValues$title_1})
output$title_2_ID = renderUI({rValues$title_2})
output$title_3_ID = renderUI({rValues$title_3})

output$thePlot = renderPlot(height=250,
                            {
                              par(mai=c(1,1,1,0.6))
                              par(mar=c(4,4,2,2) + 0.2)
                              #c(bottom, left, top, right)
                              par(pty='s')
                              plotPlightPdarkPosteriorReactive()
                            })
```

```{r makeDebuggingPanelOutput}
shinyDebuggingPanel::makeDebuggingPanelOutput(
  session, toolsInitialState = FALSE) 
```


```{r navTOCid.R.2}
#source('navTOCid.R', local=T)
```

```{r, results='asis'}
#cat("\U2B07")
# This shows you can get a fat arrow... but not in a plot.
```

```{r withDebuggingPanel}
##  <a name='debugging'>** **</a>
fluidRow(
  shinyDebuggingPanel::withDebuggingPanel() 
)
```

```{r conditionalPanelWithCheckbox}
conditionalPanelWithCheckbox = function(
  labelString, 
  filename,
  html='',
  initialValue=FALSE
) {
   labelStringNoSpaces = gsub(" ", "_", labelString)
   labelStringId = paste0(labelStringNoSpaces, 'Id')
   cbStringId = paste0('cb', labelStringId)
   if(!missing(filename))
     html = c(tagList(inclRmd(filename)), html)
   output[[labelStringId]] <- renderUI({
     list(
       checkboxInput(cbStringId, 
                     strong(em(
                       paste0("show/hide the ", labelString))),
                     value=initialValue),
       conditionalPanel(condition = paste0('input.', cbStringId),
                        html )
     )
   })
   uiOutput(labelStringId)
}
```

```{r panelOfInputs}
panelOfInputs = 
  wellPanel(strong(em("Declaring the Prior Distribution ")),
    checkboxInput(inputId= 'togglePanelOfInputs', 
                  label = 'togglePanelOfInputs',value = TRUE),
    conditionalPanel(
      "input.togglePanelOfInputs",
      wellPanel(
        numericInput("phiInput", "prior variance | group (phi)", 
                     value=0, min = 0.00, step=0.1),
        numericInput("tauInput", "shared additional variance (tau)", 
                     value=1, min = 0.00, step=0.1),
        numericInput("mu0Input", "shared prior mean", 
                     value=0.5, min = 0.001, step=0.1, max=0.999),
        actionButton("lumpID", label = "Lump"),
        actionButton("splitID", label = "Split"),
        actionButton("mixedID", label = "Mixed")
      ),
      numericInput(inputId = 'fudgeFactor', 
                   label = 'continuity fudge factor',
                   value=0.001)
    ))
```


```{r show-hide-contours}
ContoursPanelLegend = list(
#  "X:   observed data", br(),
  "L:  Dr.Lump's MP estimate", br(),
  "S:  Dr.Split's MP estimate", br(),
  "W:  Dr.Who's MP estimate",
  div(style="color:orange", 
      checkboxInput("checkPrior", 
                    "Orange = prior distribution",
                    TRUE)),
  div(style="color:blue",
      checkboxInput("checkPosterior", 
                    "Blue = posterior distribution",
                    TRUE)),
  "Shaded: 50% highest posterior region"
)
```

```{r responseRates}
output$responseRates = renderUI({
  splitLayout(HTML("Response <br>rates:"),
                HTML(paste(
                  input$mRD, '/', input$mRD+input$mND, 
                  "<br> = ",
                  round(digits=3,
                        input$mRD/(input$mRD+input$mND)))),
                HTML(paste(
                  input$mRL, '/', input$mRL+input$mNL, 
                  "<br> = ", 
                  round(digits=3,
                        input$mRL/(input$mRL+input$mNL))))
    )
  # paste(input$mRD, '/', input$mRD+input$mND, "for D, and ",
  #       input$mRL, '/', input$mRL+input$mNL, "for L.")
})
```

```{r data table}
source('dataTableComponent.R', local=TRUE)
```

```{r panelOfBifurcation}
output$fisherResult = renderUI({
    Pvalue = fisher.test(rValues$DLdata)$p.value
    div('Fisher exact test result:',
        br(),
        paste0('P = ', Pvalue, '\n')
    )
})
 
panelOfBifurcation = 
    conditionalPanelWithCheckbox(
      labelString = 'Classical bifurcated analysis',
      html = list(
  strong(em(span("P>0.05? then lump. P<0.05? then split"))),
  uiOutput('fisherResult')
#  checkboxInput('toggleShowFisher', 'Show/Hide the Fisher test', FALSE)
#)
      )
)
```



```{r UI_begins}
#### UI fluidPage####
require(shinyBS)
```
*Date: "`r date()`"     Author: "Roger Day, University of Pittsburgh"*
# OVERVIEW of this Module


```{r Overview}
conditionalPanelWithCheckbox(
  labelString = 'Overview', 
  filename = 'Overview.Rmd', html = '',
  initialValue = TRUE)
```
The general scope of the bias-variance axis in many settings is here:
```{r hide=TRUE}
interactiveSection(codeToRun="eval(parse(text=linkout('Reproducibility-lump-split-page-1.pdf')))", showResult = FALSE)
```

The list of topics developed or in development is here:
```{r topics}
conditionalPanelWithCheckbox(
  labelString = 'Topics', filename = 'topics.Rmd', initialValue=FALSE)
```

```{r submoduleTitle}
##  <a name="LSnotebookBegin"> The Lump versus Split Dilemma </a>
hr()
h2(style="text-align: center;", 'The Lump versus Split Dilemma')
hr()
```


```{r include notebook}
div(
#  list(fluidRow(column(width = 8, 
         # wellPanel(id = "leftScrollPanel",
                   # style = "overflow-y:scroll; max-height: 600px"
         # ,
         inclRmd('Submodule-LumpSplit.Rmd')
 #        ),
  # column(width = 4, 
  #       wellPanel(id = "leftScrollPanel",
  #                  style = "overflow-y:scroll; max-height: 600px"
  #        , 
         #panelOfData,
         #dataTableComponent(),
         #panelOfBifurcation,
         
)
```

```{r}
#div(list(br(),br(),br(),br(),br(),br(),br(),br()))
```
```{r include navTOCid}
#source('navTOCid.R', local=T)
```
```{r}
#div(list(br(),br(),br(),br()))
```



