```{r include=FALSE}
  content_filename = paste0("_", user, "_UserEntries_T15lumpsplit.txt")
contentFileInput = function(
    label=c('all_entries_', 'comments','answers')) {
    #https://stackoverflow.com/questions/49506469/shiny-customise-fileinput?rq=1
  thisButtonLabel = HTML(paste0("Click here to find&load the file <b>", content_filename, '</b>', "& fill boxes"))
    thisfileInput =
      fileInput(inputId = paste0(label,"FileInput"), 
              label = NULL,
              buttonLabel=thisButtonLabel,
              accept = c(
                "text/csv",
                "text/comma-separated-values,text/plain")
      )
    thisfileInput$children[[2]]$children[[2]] = NULL
    assign(paste0(label, 'FileInput'), thisfileInput, pos=1)
    thisfileInput
  }
output$contentsAdviceOutput = renderUI({
  text = div(
      style=paste(
        #'display: flex; justify-content: flex-center;',
      'color:', adviceForeground, '; background: ', adviceBackground, ';
         font-size:larger'),
    "This application page contains boxes where you can write entries.",
    br(),
    "There are 2 type of entry boxes for you:",
    tags$ul(
      tags$li(HTML(
        "'comments' (Questions and 'Aha'-discoveries)  <b>(QA)</b>)"  )),
      tags$li(HTML(
        "responses to imbedded Text Questions. <b>(TQ)</b>"))),
    
    "What you type in a box is instantly saved as a web page 'cookie'.",
    br(),
    "When you resume later in a new session (same browser),", 
    br(), 
    "these cookies will (usually) reload your previous work into the boxes.", 
    br(), 
    br(), 
    HTML("You can also save these <b>QA</b> and <b>TQ</b> answers into a file,"),
    br(),
    "and reload your saved content file from your Downloads folder-- if you'd previously saved it.", 
    br(),
    HTML("You can save these 'comments' and 'responses' to a file at any time, 
    with <b>Control-Shift-S</b>."), 
    br(), 
    "(Or, view your current entries at the bottom of this app page, and click the button there.)", 
    br(),
    "When resuming later (if the cookies didn't do the trick),",
    br(),
    "to locate and upload your saved entries, ",
    "and fill the content boxes below,", 
    "click the button below.",
    br(),
    "(Sorry-- the file upload cannot be fully automated...)",
    br(),
    "(Only currently blank entry boxes will be filled from your file, so your current entries will NOT be clobbered by empty space.)",
    br(), br(),
    "So, WHY save your entries to a file?",
    br(),
    "Because you can send your file to a friendly mentor or mentor-ly friend, to get their feedback.",
    contentFileInput('all_entries_')
  )
})

```

```{r}
observeEventForFileInput(contentType = 'all_entries_')
#observeEventForFileInput(contentType = 'comments')
#observeEventForFileInput(contentType = 'answers')
### Strange--  source() from here requires prefix "inst/T15lumpsplit"
### But it's not necessary in the main Rmd.
```


