#source('rstudio.markdownToHTML.R', local=TRUE)
source('nextNumber.R', local=TRUE)
source('interactiveSection.R', local=TRUE)
source('QandAha.R', local=TRUE)
source('TextQuestion.R', local=TRUE)
source('inclRmd.R', local=T)
source('linkout.R', local=T)
source('interactiveSection.R', local=T)
source('includeHTMLtrimmed.R', local=T)
#source('navTOCid.R', local=T)
source("Plight-Pdark-posterior-new.R", local=TRUE)
source("DrWhoBayesFactor.R")
#source('navTOCid.R', local=T)
source('dataTableComponent.R', local=TRUE)
#source('navTOCid.R', local=T)
