---
title: "Testing shinyjs in rmd"
runtime: shiny
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r shinyjs, context="server", echo=TRUE, results='hide', include=TRUE}

library(shinyjs)
useShinyjs(rmd = TRUE)
library(shinycookie)
```

```{r}

# helloJScode = 
#   "shinyjs.helloJS = function() {alert('HELLO');};"
# shinyjs::extendShinyjs(text = helloJScode, functions=c('helloJS'))

jsCode <- "shinyjs.pageCol = function(params){$('body').css('background', params);}"
shinyjs::extendShinyjs(text = jsCode, functions = c("pageCol"))

# cookieCode <- "shinyjs.getCookie = function(params){document.cookie}"
# shinyjs::extendShinyjs(text = cookieCode, functions = c("getCookie"))
# 
# cookieID = 'cookieID'
# shinycookie::initShinyCookie(cookieID, timeout = 500)
# shinycookie::updateCookie(session, TEST='humm')

```


```{r}
actionButton("button", "Click me")
div(id = "hello", "Hello!")
observeEvent(input$button, {
 toggle("hello")
})

selectInput("col", "Colour:",
                    c("white", "yellow", "red", "blue", "purple"))

```

```{r}
observeEvent(input$col, {
          js$pageCol(input$col)
        })
#print(js$getCookie())

#js$helloJS()
```
