---
title: "Testing shinyjs in rmd"
runtime: shiny
output:
  html_document:
    number_sections: yes
    toc: yes
    toc_depth: 6
    toc_float:
      collapsed: no
      smooth_scroll: no
---


```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)
options(knitr.duplicate.label = 'allow')
```
```{r, echo=FALSE}
shiny::addResourcePath("shinyjs", system.file("srcjs", package = "shinyjs"))
```
```{r, context="server"}
  require(shinyjs);

shinyjs::useShinyjs(rmd = TRUE)
```

<script src="shinyjs/inject.js"></script>

```{r}
actionButton("button", "Click me")
div(id = "hello", "Hello!")
observeEvent(input$button, {
 toggle("hello")
})
```

```{r}
jsCode <- "shinyjs.pageCol = function(params){$('body').css('background', params);}"

extendShinyjs(text = jsCode, functions = c("pageCol"))
selectInput("col", "Colour:",
            c("white", "yellow", "red", "blue", "purple"))
observeEvent(input$col, {
          js$pageCol(input$col)
        })

cookieCode = "shinyjs.retrieveCookie = function(params) {
  alert(document.cookie);
  return document.cookie;
};"
extendShinyjs(text = cookieCode, functions = c("retrieveCookie"))
actionButton("cookieButton", "retrieveCookie")
observeEvent(input$cookieButton, {
  print(js$retrieveCookie())
  #
})
```

```{r}
js$pageCol('green') # doesn't work?
```

